### PR TITLE
2024 Jan dependency updates

### LINKED ISSUE #35: Upgrade Node
I've added an nvmrc file to specify Node 16 like the package file but it should be upgraded to the latest LTS Node runtime

### PR DESCRIPTION
**Pull request by tomjn**
This should resolve #35 #36 and lay some groundwork for #21

It also upgrade socketIO, Angular, and Node

### CODE REVIEW

**Comment by tomjn** [comment]
Note that I tried updating Angular further but 1.2 moves the router into its own package making an easy upgrade a bit more involved

**Comment by tomjn** [comment]
1.2 required a routing JS be included, moving to 1.3 will require refactoring the main controller which is a bit more involved, leaving it as out of scope

**Review by kadamwhite — APPROVED** [review]
Don't have a specific understanding of #36 but the upgrade work looks solid.
I don't miss Angular 1, though....

**Comment by tomjn** [comment]
Previously it stored the socket ID on a connection, but if you
Open a new tab there's multiple connections with the same ID, so when it cleaned up one socket the other was orphaned.

Now there's an array of socket IDs!

I'd love to rebuild the UI in React with a store, just needs time which is easier said than done

**Pull request merged**
